### ISSUE TITLE
Set up your capstone project - Kanban board

### ISSUE THREAD

**Issue by aimemalaika** [aimemalaika/awesome-tv#21]
Hello, for our capstone project, we chose to create a website with data about TV series and movies. This website includes webpack, and the [TVmaze API](https://www.tvmaze.com/api), and the [Microverse involvement API](https://www.notion.so/Involvement-API-869e60b5ad104603aa6db59e08150270). In this project, we have 2 people assigned:

- @aimemalaika 
- @oyelakinG9 

[Link to the GitHub project](https://github.com/aimemalaika/awesome-tv)

**Comment by uwadonat** [comment]
Hi **@Team**, :hand: 

Good job so far! :mechanical_arm:
There are some issues that you still need to work on to go to the next project but you are almost there!

## Status: Required Changes ♻️

- [ ] Make sure your final project looks like this [Template](https://github.com/microverseinc/curriculum-react-redux/projects/1) given. you need to show four different states of the project.

 
![Screenshot from 2022-01-31 15-49-14](https://user-images.githubusercontent.com/65860678/151805387-498cefae-78a9-423c-9634-602968b8556f.png)

- [ ] As you are two members you should remove tasks for student C.

 **Kindly fix these issues and ask for another review.**

Cheers and Happy coding!👏👏👏

**Comment by aimemalaika** [comment]
Hell @uwadonat 

we have removed before all student C as for the first review comment I don't understand what you mean.

**Comment by oyelakinG9** [comment]
Thanks @uwadonat
We really appreciate, but we haven't gotten you well  😊 can you please elaboratee because we've removed student C from the task already 👏

**Comment by ZeenatLawal** [comment]
Hi @aimemalaika and @oyelakinG9, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

## Congratulations! 🎉 
![6vEo](https://user-images.githubusercontent.com/46851023/133564373-95c66227-e33a-4506-b21a-d6db9b3a2050.gif)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by oyelakinG9** [comment]
Thanks @ZeenatLawal 
We'll appreciate 🙌🙌
